/**
 * Nutrient keys are the component codes of the German Bundeslebensmittelschlüssel (BLS 4.0),
 * e.g. `ENERCC` (kcal) or `F18:3CN3`. All nutrient maps hold amounts per 100 g (foods) or
 * absolute amounts (diary entries, totals) in the unit listed in the catalog.
 *
 * The full catalog of all 138 BLS components lives in `nutrients-catalog.json`
 * (generated by `tools/bls-import`); this module defines the subset the UI shows.
 */

export type NutrientMap = Record<string, number>;

export const N = {
  kcal: 'ENERCC',
  kj: 'ENERCJ',
  protein: 'PROT625',
  fat: 'FAT',
  carbs: 'CHO',
  fiber: 'FIBT',
  sugar: 'SUGAR',
  satFat: 'FASAT',
  salt: 'NACL',
  sodium: 'NA',
  alcohol: 'ALC',
} as const;

export type NutrientKey = (typeof N)[keyof typeof N];

export interface NutrientInfo {
  code: string;
  de: string;
  en: string;
  unit: string;
  group?: string;
  groupEn?: string;
}

/** Nutrients shown in the UI (feature #7: fiber, sugar, salt, saturated fat on top of the macros). */
export const DISPLAY_NUTRIENTS: readonly NutrientInfo[] = [
  { code: N.kcal, de: 'Energie', en: 'Energy', unit: 'kcal' },
  { code: N.protein, de: 'Protein', en: 'Protein', unit: 'g' },
  { code: N.fat, de: 'Fett', en: 'Fat', unit: 'g' },
  { code: N.carbs, de: 'Kohlenhydrate', en: 'Carbohydrates', unit: 'g' },
  { code: N.fiber, de: 'Ballaststoffe', en: 'Fibre', unit: 'g' },
  { code: N.sugar, de: 'Zucker', en: 'Sugars', unit: 'g' },
  { code: N.satFat, de: 'Gesättigte Fettsäuren', en: 'Saturated fat', unit: 'g' },
  { code: N.salt, de: 'Salz', en: 'Salt', unit: 'g' },
];

/** Keys stored in the compact (client-side, offline) BLS variant. */
export const COMPACT_NUTRIENTS: readonly string[] = [
  N.kcal,
  N.kj,
  N.protein,
  N.fat,
  N.carbs,
  N.fiber,
  N.sugar,
  N.satFat,
  N.salt,
  N.sodium,
  N.alcohol,
];

export const MICRO_NUTRIENTS = [N.fiber, N.sugar, N.satFat, N.salt] as const;
export type MicroKey = (typeof MICRO_NUTRIENTS)[number];

/**
 * Energy factors (kcal per g). Macro-energy shares (`energyBreakdown`) use protein, fat and carbs
 * (4/9/4); the custom food kcal automatic adds fiber like the EU label rule (`kcalFromMacrosEu`).
 */
export const KCAL_PER_G = { protein: 4, fat: 9, carbs: 4, alcohol: 7, fiber: 2 } as const;

/** Nutrients that count for the kcal automatic of custom foods. */
const EU_ENERGY = [
  [N.protein, KCAL_PER_G.protein],
  [N.carbs, KCAL_PER_G.carbs],
  [N.fat, KCAL_PER_G.fat],
  [N.fiber, KCAL_PER_G.fiber],
] as const;

/**
 * kcal from the macros like an EU nutrition label (Regulation 1169/2011, Annex XIV):
 * 4 × protein + 4 × carbs + 9 × fat + 2 × fiber. Missing values count as 0.
 */
export function kcalFromMacrosEu(map: NutrientMap): number {
  return EU_ENERGY.reduce((sum, [code, f]) => sum + (map[code] ?? 0) * f, 0);
}

/**
 * Whether stored kcal are the automatic ones (no mode flag is stored): they match
 * `kcalFromMacrosEu` to 0.5 kcal and at least one of its nutrients is above 0.
 */
export function isAutoKcal(map: NutrientMap): boolean {
  const kcal = map[N.kcal];
  if (kcal === undefined || !EU_ENERGY.some(([code]) => (map[code] ?? 0) > 0)) return false;
  return Math.abs(kcal - kcalFromMacrosEu(map)) <= 0.5;
}

/** Salt (g) from sodium (mg): NaCl = Na × 2.5 (EU Regulation 1169/2011, Annex XIV; also the BLS formula). */
export function saltFromSodiumMg(sodiumMg: number): number {
  return (sodiumMg * 2.5) / 1000;
}

export function sodiumMgFromSalt(saltG: number): number {
  return (saltG / 2.5) * 1000;
}

/** kcal from kJ (1 kcal = 4.184 kJ). */
export function kcalFromKj(kj: number): number {
  return kj / 4.184;
}

export function kjFromKcal(kcal: number): number {
  return kcal * 4.184;
}

/**
 * Fills derivable values so every food has the keys the UI relies on:
 * kcal↔kJ and salt↔sodium. Never overwrites existing values.
 */
export function completeNutrients(input: NutrientMap): NutrientMap {
  const out: NutrientMap = { ...input };
  const { [N.kcal]: kcal, [N.kj]: kj, [N.salt]: salt, [N.sodium]: sodium } = input;
  if (kcal === undefined && kj !== undefined) out[N.kcal] = kcalFromKj(kj);
  if (kj === undefined && kcal !== undefined) out[N.kj] = kjFromKcal(kcal);
  if (salt === undefined && sodium !== undefined) out[N.salt] = saltFromSodiumMg(sodium);
  if (sodium === undefined && salt !== undefined) out[N.sodium] = sodiumMgFromSalt(salt);
  return out;
}

/** Picks a subset of keys (missing keys are omitted, not zeroed). */
export function pickNutrients(map: NutrientMap, keys: readonly string[]): NutrientMap {
  const out: NutrientMap = {};
  for (const k of keys) {
    const v = map[k];
    if (v !== undefined) out[k] = v;
  }
  return out;
}
